version: '3'
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql_dev
    ports:
      - ${REAL_MYSQL_PORT}:3306
#    command:
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_general_ci
#      --explicit_defaults_for_timestamp=true
#      --lower_case_table_names=1
#      --max_allowed_packet=128M
#      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - ${MYSQL_DIR}/data:/var/lib/mysql
      - ${MYSQL_DIR}/my.cnf:/etc/my.cnf
      - ${MYSQL_DIR}/logs:/logs
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    restart: always
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis_dev
    ports:
      - ${REAL_REDIS_PORT}:6379
    volumes:
      - ${REDIS_DIR}/data:/data
      - ${REDIS_DIR}/redis.conf:/etc/redis/redis.conf
#      - ${REDIS_DIR}/logs/redis.log:/logs/redis.log
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
